version: 2
sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: parcel
        identifier: raw_cc_parcel
        tests:
          - unique:
              column_name: Parcel_id
          - not_null:
              column_name: Parcel_id
        description: suivi global des livraisons (dates)
      - name: parcel_product
        identifier: raw_cc_parcel_product
        tests:
          - unique:
              column_name: (ParCEL_id || '-' || Model_mAME)
          - not_null:
              column_name: (ParCEL_id || '-' || Model_mAME)
        description: suivi du contenu des colis


models:
  - name: stg_raw__parcel
    columns:
      - name: parcel_id
        tests:
          - unique
          - not_null
  - name: stg_raw__parcel_product
    tests:
      - unique: 
          column_name: (parcel_id || '-' || model_name)
      - not_null:
          column_name: (parcel_id || '-' || model_name)
  - name: product_by_parcel
    columns:
      - name: parcel_id
        tests:
          - unique
          - not_null